language: scala
scala:
- 2.10.4
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=dev
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: LTyL6LDsIQ8uulWUZzd6rltIWI9L4YssjW6Xr+SnhQNotj6JGNm4ED5DLPZJCJpVws1f8KEOz5yWDCFclvNlgT9r2wapCh9yestT90mWRJEzR0j9h2CmFSyL0cwuHPLhqlNeeWxYLStApVfQJjq1A0ZBN+lxUonkniGYLVwirUY=
  - secure: c9p71a9b+J+KC+f//r6hhTl8mdUSGXij4Y2RW+wTzUNwTMxWP/4rOhKAlEHLAZGMrTb4yaqysSMW1MimzvPeN53DMvIJFK7Byq+IPgyef+L24ejbLu4Vk+oykQPYK7p+KaeS9lFTcfNnHFmdn9QkG57Y7WJve8XwzR++yixBk68=
  - secure: d3HurQaFQA9GRUrKRD4WdTDjqBW/YbCFtR9vvV3qTygUu7C7OCxJwP6Rg3UpSdtzG6R/uVEJIQ20CgGfBhKebmLPVo7NMKp96e45bn1PyLL20J3t5832vVxjHr1s+SU3Tc3apOQNjs+KGTYChx3HFEt5tEQH7BYWJEsdoac4i7Q=
  - secure: GvT2YRaPvkEEDfIQ249BLQmXr+l2WwXwaG7JWBCtY7gS0B6e1jHqDCOfAh83cw+37YmJqLl26fPwZnpVL8L2iFC2nXk03MPepU4X1w2cicAboVKpF9TPV2A9T5gUuXKkXMKJFtH7r5K6haagNqsUXsNgsD4MWiUj2px0U3uHJ3c=
  - secure: og1MVcJbEMji2IZ933caBoYAw1ba+RXpVHQp3G0TpnJY/0fVcJbI7oRQQTnOvMJjuy39SYJP0RapJkFK06mrWlw924ixC+h+ZrRXSFEtBA3S7Qraep2PqfbhsZyvpyEbHmS3iYzmUzzC3w/vKmi2JiJOgT0r9HCkHBUzDrDO2TA=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- gem install sass
script:
- cd public
- npm install
- bower install
- grunt release
- cd ..
- sbt test
deploy:
  provider: heroku
  api_key:
    secure: To9IEKT4ppYgFW7vHVfC5s5FHzxALA+/Krg9fLv8Fx9BI3rMB91yN+MfE0yhWySaTs8BEHfAdOBN/zvWcXGyhpta10TtvKs04DzZt9foP+MPbRDbE5WEQ9M2n3uAy10ACX2Kxj3ebv3d97I8TYD2qfVBArIIOG29FZlJsRDYIWg=
  skip_cleanup: true
  app:
    develop: bridge-development
