language: scala
scala:
- 2.10.4
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=local
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: G4K1NYn4/Mw191bfRvKXnLCIkTfVOWIPkbvbsZth442fS57VoumOqLSKRegiPHsRGEecJhhDhqt51k+FkwdFSNjrTcm6wEHGoqlF+vO7NYD6EuVWq/4VV37gdi2KZ4OLLw2c35U3nhIXAWkGbpJMnOmKg1fblkKwTlh+c7IHFgw=
  - secure: FdzZAXqnI7SBNjmshNL0NhwuCsL1F3DNkHayMoNeB3DDH/hG89ghWQbd/7mOWjbR0HgHL7zxIjoqB5YfyG5yD+74+Te/nrEd4VqvWuZNNYFrXBwEWKme8Ao8MM2Tw7InTC6QpgG1Rnypb3WsTRM6gcO48oofDsD7RFViNG6ifYo=
  - secure: Udf2FDYsBixxt2UkH6XgymQ/VXj3cilCqdc06ED3FtIPwP+SM8LI6UzzoBIirBAfCz/lS5aEx/IVxBzbWJoxSoQ3hxqCAmWS9ZzLeSQngfcg0pqkVZOG5QGhJ4sbrjnVFjvJl1E9xIrrT6bNYDw/zsFVgVBLDrHc9wf+kHQGcDc=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- gem install sass
script:
- cd public
- npm install
- bower install
- grunt release
- cd ..
- sbt test
deploy:
  provider: heroku
  api_key:
    secure: To9IEKT4ppYgFW7vHVfC5s5FHzxALA+/Krg9fLv8Fx9BI3rMB91yN+MfE0yhWySaTs8BEHfAdOBN/zvWcXGyhpta10TtvKs04DzZt9foP+MPbRDbE5WEQ9M2n3uAy10ACX2Kxj3ebv3d97I8TYD2qfVBArIIOG29FZlJsRDYIWg=
  skip_cleanup: true
  app:
    develop: bridge-development
