language: scala
scala:
- 2.10.4
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=stub
  - secure: Y56vwBuVI0boZHdJCCGdpEOLGb1Dsa/ZyEuWFedFftEID2qh1WwYPd1YApOUKU/Mzwf8KCGWFue6W5DupkdfBOqPR6bu5PgABg5QObn3yn8stG/wlTU726OfgQNBVHIbkz8VJ8u1W8CxS7mY+VY0mRLir/uotx57Yecugr3cRY8=
  - secure: XN8uT1mdvbNRtEZLU6znAenxkWuC8nQGn0u1ajUW4CkCIrMw39sEsH8TVytdzKoWQ5GGnD6dHwYID7QGzy+n8N6zfAOuJw1kef3MxcbS6nQ1+Vtu9WbIcTAhcXq3VcnVp1IvciPYbB3/JKF97QfpuTDXFRgLCVj316oqPq6GouE=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- gem install sass
script:
- cd public
- npm install
- bower install
- grunt release
- cd ..
- sbt test
deploy:
  provider: heroku
  api_key:
    secure: To9IEKT4ppYgFW7vHVfC5s5FHzxALA+/Krg9fLv8Fx9BI3rMB91yN+MfE0yhWySaTs8BEHfAdOBN/zvWcXGyhpta10TtvKs04DzZt9foP+MPbRDbE5WEQ9M2n3uAy10ACX2Kxj3ebv3d97I8TYD2qfVBArIIOG29FZlJsRDYIWg=
  skip_cleanup: true
  app:
    develop: bridge-development
