language: scala
scala:
- 2.11
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=dev
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: GvT2YRaPvkEEDfIQ249BLQmXr+l2WwXwaG7JWBCtY7gS0B6e1jHqDCOfAh83cw+37YmJqLl26fPwZnpVL8L2iFC2nXk03MPepU4X1w2cicAboVKpF9TPV2A9T5gUuXKkXMKJFtH7r5K6haagNqsUXsNgsD4MWiUj2px0U3uHJ3c=
  - secure: Z9NMpRqgtAhaNQLBeSh0iJTgKeNpB3uY4xoYGPNNhDH+rhFe+Urh6RZxfrkF1stAuZXKS1GJe2Kln2GAm2F21DMGagiopcZZIDM456kTDni7A78v/CQR5Sa+PHWk5fITOWTAJSee/pzHaEo7+AIWxhP5DxZah/jJdS3FYM26v/s=
  - secure: aSwn+AOcO2iGFEWcDYJebjglcbADKmlNs1W8NtUjGEFOmuT6nIxyQPva7FAlU4GojnazGQvEwVolFh6D7NPgHVENStflGhUcRLRqeiJV1gBgTV+ot00HRZjEJSacljFFBwQbRW4NfUDzOrE/FClkyCCJnRbKWg3dKONe2dVNEZg=
  - secure: VSoOGViuAi98dBrveHw61gHz0zersdtn8raolu/uzpNQEI1csMdVr09SokygjtiSEt5uIVNma1zkuABRAEgfncT3rYqPq0mdeM+hxPEz2igxEMUXYHx3H9Osbo5oOrTZXnRg18kmzyupUQ98L5Y6/8lg67sgJkPBJEx9dwNKhMY=
  - secure: kTMnfr/AKb5Bp9HuNENNKHsMB+sdlxzIOptVFhA6Gg4poTw+6Y93yUHmqxtAh6WCnihG00877+uQw5IKUww0oL4ppbYgQKwyafhMeIkEpKG/Dycc80oklQe/n7mqHsgRpX3zCeKJG3AZmKsDj/l/WN1i01n68JMeOasGFFQYXpg=
  - secure: fFyFcdKI0utZGSTkeoukkVb4GHUuIpK5VA639prJHyrDhi/rxL8jU8A82av+lYBJHrCRN3ZMfgVxui4uLmqaSacPAcIBIeHyOFq9zEir7TDw8nXhsnAVLJt25i6L731hlEuNDfnroaHV5BCgfkECJcXee07UXhEKFk7vH80KeAk=
  - secure: LtnBJBkSMSzXJlmZQLs3BahpAN0rvF4jRyMuzMK6JaBFqPyiQx9TRRre1wfVsa5KfbnWfLUBEh0XgbbEAzNpVVrB90cfFGUZXgPQKHJI12Z+wqfTGg+f9z63oKjFBw3xe6VWAvzlbMNvoImxnSgHwhluZW9ToXoW9l/oKNLz6os=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- gem install sass
script:
- cd public
- bash update-js.sh
- cd ..
- sbt test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: To9IEKT4ppYgFW7vHVfC5s5FHzxALA+/Krg9fLv8Fx9BI3rMB91yN+MfE0yhWySaTs8BEHfAdOBN/zvWcXGyhpta10TtvKs04DzZt9foP+MPbRDbE5WEQ9M2n3uAy10ACX2Kxj3ebv3d97I8TYD2qfVBArIIOG29FZlJsRDYIWg=
  skip_cleanup: true
  app:
    develop: bridge-develop
    prod: bridge-prod
