language: scala
scala:
- 2.10.4
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=local
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: TBIgP2JOaRtHEd0IyesxVedIVo7idYso51Q2vBVMsyZCHF7KyZsBqX3CMaQGbRTwfdLcHz3Pf6Vke2ewG9t+8NZPcwTuZO4klV/5Bs7cvQpLn8ZyOSWtJB56JR6vJTvpt8do5ODjDcIad0E13SMKDRhQdc9KD1zV6prcIxQN03U=
  - secure: s8P5xLHcnogt6r+ebj5eVoGlmR5CTAdUl0ZyssvbqdMVwus3j3r6ZW9NwL67r+K96s3Ukk1QQS2xQj1WhFPeoetkJI3JbFeeCeqNI3LrGf4gdrONDPS0v4jbWeWpTVTlf+DFtd3tm44ew18KRpmxybRDK48Ux0mJG5Z4WHrxerk=
  - secure: mcvuu7eDWdQX7YcS0hfM7uEgjxgeyMNYNtN+hljBhI/Lc0cfUSMjp0rDQiwjTLYQNjjJd+ebO8v/nmE450kB7pz8QDCqpXiywVQe1cb5PNF8SO5JwmFAwM3ACS8pvi5QEvtr0VIF7YOOU3GK1MtzbJMyBneYF+CryImAMpcl2lE=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- gem install sass
script:
- cd public
- npm install
- bower install
- grunt release
- cd ..
- sbt test
deploy:
  provider: heroku
  api_key:
    secure: To9IEKT4ppYgFW7vHVfC5s5FHzxALA+/Krg9fLv8Fx9BI3rMB91yN+MfE0yhWySaTs8BEHfAdOBN/zvWcXGyhpta10TtvKs04DzZt9foP+MPbRDbE5WEQ9M2n3uAy10ACX2Kxj3ebv3d97I8TYD2qfVBArIIOG29FZlJsRDYIWg=
  skip_cleanup: true
  app:
    develop: bridge-development
